import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { affiliateLinks, titles } from '@/db/schema'
import { eq } from 'drizzle-orm'

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * CONFIGURAÇÃO GLOBAL DE AFILIADOS (Anime2Cap)
 * ─────────────────────────────────────────────────────────────────────────────
 * 
 * Se você precisar alterar as plataformas, parceiros, URLs de busca ou etiquetas,
 * altere as chaves abaixo.
 * 
 * As tags de afiliados da Amazon e Crunchyroll podem ser configuradas no arquivo .env
 * do projeto (ex: Vercel) sem mexer no código:
 * 
 * - NEXT_PUBLIC_AMAZON_TAG=sua-tag-amazon
 * - NEXT_PUBLIC_CRUNCHYROLL_REF=seu-ref-crunchyroll
 * 
 */
const PLATFORM_CONFIGS: Record<string, { 
  domain: string, 
  urlPattern: (name: string) => string, 
  label: Record<string, string> // Dicionário de traduções localizadas
}> = {
  amazon: {
    domain: 'amazon.com.br',
    urlPattern: (name: string) => {
      const tag = process.env.NEXT_PUBLIC_AMAZON_TAG || 'anime2cap-20'
      // Busca pelo mangá oficial do título
      return `https://www.amazon.com.br/s?k=${encodeURIComponent(name + ' mangá volume 1')}&tag=${tag}`
    },
    label: {
      pt: 'Comprar Mangá',
      en: 'Buy Manga',
      ja: 'マンガを買う'
    }
  },
  crunchyroll: {
    domain: 'crunchyroll.com',
    urlPattern: (name: string) => {
      const ref = process.env.NEXT_PUBLIC_CRUNCHYROLL_REF || 'anime2cap'
      // Busca pelo anime na Crunchyroll
      return `https://www.crunchyroll.com/series/search?q=${encodeURIComponent(name)}&ref=${ref}`
    },
    label: {
      pt: 'Assistir na Crunchyroll',
      en: 'Watch on Crunchyroll',
      ja: 'Crunchyrollで観る'
    }
  }
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const searchParams = request.nextUrl.searchParams
  const locale = searchParams.get('locale') || 'en'

  // Extract ID from slug if possible (format: "123-slug" or just "123")
  let titleId: number | null = null
  if (/^\d+$/.test(slug)) {
    titleId = parseInt(slug)
  } else if (/^\d+-/.test(slug)) {
    titleId = parseInt(slug.split('-')[0])
  }

  try {
    let titleName = slug.replace(/-/g, ' ')

    // 1. Look up title by ID or slug in our DB
    if (!titleId) {
      const titleResult = await db
        .select({ id: titles.id, name: titles.name })
        .from(titles)
        .where(eq(titles.slug, slug))
        .limit(1)

      if (titleResult.length > 0) {
        titleId = titleResult[0].id
        titleName = titleResult[0].name
      }
    } else {
      const titleResult = await db
        .select({ name: titles.name })
        .from(titles)
        .where(eq(titles.id, titleId))
        .limit(1)

      if (titleResult.length > 0) {
        titleName = titleResult[0].name
      }
    }

    // 2. Fetch existing manual affiliate links overrides from DB
    const dbLinks = titleId
      ? await db
          .select()
          .from(affiliateLinks)
          .where(eq(affiliateLinks.titleId, titleId))
      : []

    // 3. Merge DB overrides with auto-generated links
    const existingPlatforms = new Set(dbLinks.map(l => l.platform))
    const responseLinks = []

    // Add manual DB overrides first
    for (const link of dbLinks) {
      // Localized label if not manually defined
      const defaultLabel = PLATFORM_CONFIGS[link.platform]?.label[locale] || PLATFORM_CONFIGS[link.platform]?.label['en'] || link.platform
      responseLinks.push({
        id: link.id,
        platform: link.platform,
        url: link.url,
        label: link.label || defaultLabel,
        isAutoGenerated: false,
      })
    }

    // Generate automatic links for platforms that don't have DB overrides
    for (const [platform, config] of Object.entries(PLATFORM_CONFIGS)) {
      if (!existingPlatforms.has(platform)) {
        const defaultLabel = config.label[locale] || config.label['en']
        responseLinks.push({
          id: `auto-${platform}`,
          platform,
          url: config.urlPattern(titleName),
          label: defaultLabel,
          isAutoGenerated: true,
        })
      }
    }

    return NextResponse.json({
      affiliates: responseLinks,
      titleName,
    })
  } catch (error) {
    console.error('[API affiliates] Error:', error)
    return NextResponse.json({ affiliates: [] })
  }
}
