/**
 * @jest-environment node
 */
import { GET } from './route'
import { NextRequest } from 'next/server'

// Mocks do banco de dados Drizzle
const mockSelect = jest.fn()

jest.mock('@/lib/db', () => ({
  db: {
    select: (...args: any[]) => mockSelect(...args),
  }
}))

describe('GET /api/title/[slug]/affiliates', () => {
  beforeEach(() => {
    jest.clearAllMocks()

    // Configura o fluxo da 1ª chamada (Lookup do título pelo id)
    mockSelect.mockReturnValueOnce({
      from: jest.fn().mockReturnValueOnce({
        where: jest.fn().mockReturnValueOnce({
          limit: jest.fn().mockResolvedValueOnce([{ name: 'Naruto' }])
        })
      })
    })

    // Configura o fluxo da 2ª chamada (Links de afiliados salvos no DB)
    mockSelect.mockReturnValueOnce({
      from: jest.fn().mockReturnValueOnce({
        where: jest.fn().mockResolvedValueOnce([
          { id: '1', titleId: 1, platform: 'amazon', url: 'https://amazon.com/dp/XYZ', label: null, isAutoGenerated: false }
        ])
      })
    })
  })

  it('returns affiliate links for a title', async () => {
    const req = new NextRequest('http://localhost/api/title/1-naruto/affiliates?locale=pt')
    const res = await GET(req, { params: Promise.resolve({ slug: '1-naruto' }) })
    const data = await res.json()

    expect(res.status).toBe(200)
    expect(data.affiliates).toBeDefined()
    expect(data.affiliates.length).toBe(2) // 1 do DB mock + 1 gerado automaticamente para Crunchyroll
    
    // Verifica link manual do DB
    expect(data.affiliates[0].id).toBe('1')
    expect(data.affiliates[0].platform).toBe('amazon')
    expect(data.affiliates[0].url).toBe('https://amazon.com/dp/XYZ')
    
    // Verifica link automático gerado
    expect(data.affiliates[1].platform).toBe('crunchyroll')
    expect(data.affiliates[1].isAutoGenerated).toBe(true)
  })
})
