'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { ExternalLink, ShoppingCart, Play, Sparkles } from 'lucide-react'
import { useTranslations, useLocale } from 'next-intl'

interface AffiliateLink {
  id: string
  platform: string
  url: string
  label: string
  isAutoGenerated: boolean
}

interface AffiliateButtonsProps {
  titleId: number
}

// Icons registry for different platforms
const platformIcons: Record<string, React.ReactNode> = {
  amazon: <ShoppingCart className="w-4 h-4" />,
  crunchyroll: <Play className="w-4 h-4" />,
}

// Custom brand styling for supported platforms (using subtle premium colors)
const platformStyles: Record<string, string> = {
  amazon: 'bg-[#FF9900]/10 hover:bg-[#FF9900]/20 text-[#FF9900] border-[#FF9900]/20 hover:border-[#FF9900]/40 shadow-sm shadow-[#FF9900]/5',
  crunchyroll: 'bg-[#F47521]/10 hover:bg-[#F47521]/20 text-[#F47521] border-[#F47521]/20 hover:border-[#F47521]/40 shadow-sm shadow-[#F47521]/5',
}

export function AffiliateButtons({ titleId }: AffiliateButtonsProps) {
  const t = useTranslations('TitlePage')
  const locale = useLocale()
  const [links, setLinks] = useState<AffiliateLink[]>([])
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    let isMounted = true
    fetch(`/api/title/${titleId}/affiliates?locale=${locale}`)
      .then(res => res.json())
      .then(data => {
        if (isMounted) {
          setLinks(data.affiliates || [])
          setIsLoading(false)
        }
      })
      .catch(() => {
        if (isMounted) {
          setIsLoading(false)
        }
      })
    return () => {
      isMounted = false
    }
  }, [titleId, locale])

  if (isLoading || links.length === 0) return null

  return (
    <div className="flex flex-col gap-3.5 select-none" aria-label="Onde assistir e ler">
      <span className="text-[10px] font-black uppercase tracking-widest text-paper/40 font-body flex items-center gap-1.5">
        <Sparkles className="w-3.5 h-3.5 text-brand-cherry/80" />
        {t('affiliateSectionTitle') || 'Links de Afiliados'}
      </span>
      <div className="flex flex-wrap gap-2.5">
        {links.map((link, idx) => (
          <motion.div
            key={link.id}
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.3, delay: idx * 0.05 }}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
          >
            <a
              href={link.url}
              target="_blank"
              rel="noopener noreferrer sponsored"
              className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border text-xs font-bold uppercase tracking-widest transition-all duration-200 font-body select-text ${
                platformStyles[link.platform] || 'bg-white/5 hover:bg-white/10 text-paper/60 hover:text-paper border-white/10 hover:border-white/20'
              }`}
            >
              {platformIcons[link.platform] || <ExternalLink className="w-4 h-4" />}
              {link.label}
            </a>
          </motion.div>
        ))}
      </div>
    </div>
  )
}
